<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Symfony\Component\Process\Process;

/**
 * Purges all test transaction data ahead of real go-live, per the user's own
 * 5-phase protocol: backup -> classify -> dry-run -> execute -> verify. Each
 * phase is a separate invocation so the user can review output and stop
 * between phases; `execute` additionally requires typing the exact
 * confirmation phrase as an option, matching the phase-gate they specified.
 *
 * Table lists below were verified directly against database/migrations
 * (Schema::create names), not assumed from typical ERP conventions.
 */
class CleanupTestingDataCommand extends Command
{
    protected $signature = 'cleanup:testing-data
        {phase : backup|classify|dry-run|execute|verify}
        {--confirm= : Must be exactly "LANJUT HAPUS" to run the execute phase}';

    protected $description = 'Phase-gated purge of test transaction data, preserving master/administration data.';

    /** Maintenance/Administration data — never touched. */
    private const MASTER_TABLES = [
        'companies', 'branches', 'fiscal_years', 'accounting_periods',
        'chart_of_accounts', 'report_account_mappings', 'currencies', 'taxes',
        'terms_of_payments', 'uoms', 'item_groups', 'items', 'item_warehouse_prices',
        'miscellaneous_items', 'warehouses', 'customers', 'suppliers', 'sales_persons',
        'naming_series', 'purchase_settings', 'import_mapping_presets', 'users',
        'roles', 'permissions', 'model_has_roles', 'model_has_permissions', 'role_has_permissions',
    ];

    /**
     * Doesn't cleanly fit either bucket — not deleted by `execute`, but flagged
     * every time `classify`/`dry-run` runs so the user makes the call, not me.
     */
    private const AMBIGUOUS_TABLES = [
        'sales_targets' => 'Admin-entered period targets, not generated by any document. Default: KEEP.',
        'audit_logs' => 'Logs edits to master data too (e.g. price changes), not just transactions. Default: KEEP.',
    ];

    /**
     * Transactional tables, child-to-parent. Order matters: every cross-reference
     * here is restrictOnDelete in the schema, so deleting out of order throws a
     * FK violation immediately (transaction rolls back, no partial damage) rather
     * than silently leaving orphans.
     */
    private const DELETE_ORDER = [
        'document_attachments', 'document_timelines', 'approval_flows', 'import_batches',
        'payment_allocations', 'receipt_entries',
        'payment_entry_allocations', 'payment_entry_expense_lines', 'payment_entries',
        'invoice_change_requests',
        'credit_note_items', 'credit_notes',
        'debit_note_items', 'debit_notes',
        'invoice_deliveries', 'invoice_sales_orders', 'invoice_items', 'invoices',
        'accounts_receivables',
        'delivery_items', 'deliveries',
        'sales_order_items', 'sales_orders',
        'purchase_return_items', 'purchase_returns',
        'purchase_invoice_goods_receipts', 'purchase_invoice_purchase_orders', 'purchase_invoice_items', 'purchase_invoices',
        'accounts_payables',
        'goods_receipt_items', 'goods_receipts',
        'purchase_order_items', 'purchase_orders',
        'journal_entry_lines', 'journal_entries',
        'stock_ledgers', 'stock_ins',
        'fifo_layer_consumptions', 'fifo_layers',
        'stock_adjustment_items', 'stock_adjustments',
        'stock_transfer_items', 'stock_transfers',
        'issue_stock_items', 'issue_stocks',
        'receipt_stock_items', 'receipt_stocks',
        'opening_stock_items', 'opening_stocks',
    ];

    public function handle(): int
    {
        return match ($this->argument('phase')) {
            'backup' => $this->runBackup(),
            'classify' => $this->runClassify(),
            'dry-run' => $this->runDryRun(),
            'execute' => $this->runExecute(),
            'verify' => $this->runVerify(),
            default => $this->invalidPhase(),
        };
    }

    private function invalidPhase(): int
    {
        $this->error('Phase must be one of: backup, classify, dry-run, execute, verify');

        return self::FAILURE;
    }

    // ------------------------------------------------------------------
    // TAHAP 1 — BACKUP
    // ------------------------------------------------------------------
    private function runBackup(): int
    {
        $connection = config('database.default');
        $conf = config("database.connections.{$connection}");

        if ($connection !== 'mysql') {
            $this->error("Only 'mysql' is supported by this command (default connection is '{$connection}'). Take a backup manually for this driver.");

            return self::FAILURE;
        }

        $dir = storage_path('app/backups');
        File::ensureDirectoryExists($dir);

        $filename = 'backup_before_cleanup_'.now()->format('Ymd_Hi').'.sql';
        $path = $dir.DIRECTORY_SEPARATOR.$filename;

        $this->info("Running mysqldump for database '{$conf['database']}'...");

        $process = new Process([
            'mysqldump',
            '--single-transaction',
            '--quick',
            '--routines',
            '--triggers',
            '-h', $conf['host'],
            '-P', (string) $conf['port'],
            '-u', $conf['username'],
            $conf['database'],
        ], env: ['MYSQL_PWD' => $conf['password']], timeout: 600);

        $process->run(function ($type, $buffer) use ($path) {
            if ($type === Process::OUT) {
                File::append($path, $buffer);
            }
        });

        if (! $process->isSuccessful()) {
            $this->error('mysqldump failed: '.$process->getErrorOutput());
            @unlink($path);

            return self::FAILURE;
        }

        clearstatcache();
        $bytes = filesize($path);

        if ($bytes === false || $bytes < 1024) {
            $this->error("Backup file looks wrong (size: {$bytes} bytes). Not trusting it — investigate before proceeding.");

            return self::FAILURE;
        }

        $this->info('Backup created successfully.');
        $this->line("  Path: {$path}");
        $this->line('  Size: '.number_format($bytes / 1024 / 1024, 2).' MB');
        $this->line('');
        $this->warn('Copy this file off the VPS before continuing (a mysqldump next to the DB it backs up is not a real backup).');

        return self::SUCCESS;
    }

    // ------------------------------------------------------------------
    // TAHAP 2 — CLASSIFY
    // ------------------------------------------------------------------
    private function runClassify(): int
    {
        $this->info('MASTER / STATIS — will NOT be touched:');
        $this->table(['Table', 'Rows'], $this->countRows(self::MASTER_TABLES));

        $this->line('');
        $this->warn('AMBIGUOUS — not deleted by `execute`, review before proceeding:');
        foreach (self::AMBIGUOUS_TABLES as $table => $reason) {
            $count = DB::table($table)->count();
            $this->line("  {$table} ({$count} rows): {$reason}");
        }

        $this->line('');
        $this->error('TRANSACTIONAL / TESTING — WILL be deleted by `execute`:');
        $this->table(['Table', 'Rows'], $this->countRows(self::DELETE_ORDER));

        return self::SUCCESS;
    }

    // ------------------------------------------------------------------
    // TAHAP 3 — DRY RUN (report only, no writes)
    // ------------------------------------------------------------------
    private function runDryRun(): int
    {
        $this->info('Rows that WOULD be deleted:');
        $rows = $this->countRows(self::DELETE_ORDER);
        $this->table(['Table', 'Rows'], $rows);
        $total = array_sum(array_column($rows, 1));
        $this->line("Total rows: {$total}");

        $this->line('');
        $this->info('Stock reset plan:');
        $stockCount = DB::table('items')->where('current_stock', '!=', 0)->count();
        $stockSum = DB::table('items')->sum('current_stock');
        $this->line("  {$stockCount} item(s) currently have non-zero current_stock (sum: {$stockSum}).");
        $this->line('  current_stock is a cache only (source of truth is stock_ledgers, which is being wiped) — plan: reset ALL items.current_stock to 0.');
        $this->line('  No separate opening-balance column exists; Opening Stock documents are themselves transactional and get deleted too. Re-enter opening stock manually after cleanup if needed.');

        $this->line('');
        $this->info('Document numbering reset plan:');
        $series = DB::table('naming_series')->where('current_number', '>', 0)->get(['module', 'document_type', 'current_number']);
        if ($series->isEmpty()) {
            $this->line('  No naming_series counters are above 0 — nothing to reset.');
        } else {
            $this->table(['Module', 'Document Type', 'Current Number -> Reset To'],
                $series->map(fn ($s) => [$s->module, $s->document_type, "{$s->current_number} -> 0"])->all());
        }
        $this->line('  naming_series ROWS are kept (they are config, not test data) — only current_number is reset.');

        $this->line('');
        $this->warn('STOP. Review this plan. Run: php artisan cleanup:testing-data execute --confirm="LANJUT HAPUS" only after explicit confirmation.');

        return self::SUCCESS;
    }

    // ------------------------------------------------------------------
    // TAHAP 4 — EXECUTE
    // ------------------------------------------------------------------
    private function runExecute(): int
    {
        if ($this->option('confirm') !== 'LANJUT HAPUS') {
            $this->error('Refusing to run: pass --confirm="LANJUT HAPUS" (exact phrase) to proceed.');

            return self::FAILURE;
        }

        $backupExists = File::exists(storage_path('app/backups')) && File::glob(storage_path('app/backups/backup_before_cleanup_*.sql')) !== [];
        if (! $backupExists) {
            $this->error('No backup_before_cleanup_*.sql found in storage/app/backups. Run the `backup` phase first — refusing to proceed without one.');

            return self::FAILURE;
        }

        $masterCountsBefore = $this->snapshotCounts(self::MASTER_TABLES);

        $deleted = [];

        DB::beginTransaction();

        try {
            foreach (self::DELETE_ORDER as $table) {
                $deleted[$table] = DB::table($table)->delete();
            }

            DB::table('items')->update(['current_stock' => 0]);
            DB::table('naming_series')->update(['current_number' => 0]);

            $masterCountsAfter = $this->snapshotCounts(self::MASTER_TABLES);
            if ($masterCountsAfter !== $masterCountsBefore) {
                throw new \RuntimeException('Master table row counts changed during cleanup — aborting, this should be impossible.');
            }

            DB::commit();
        } catch (\Throwable $e) {
            DB::rollBack();
            $this->error('Execution failed, transaction rolled back — no data was changed: '.$e->getMessage());

            return self::FAILURE;
        }

        $this->info('Cleanup executed successfully. Rows deleted per table:');
        $this->table(['Table', 'Rows Deleted'], collect($deleted)->map(fn ($n, $t) => [$t, $n])->values()->all());
        $this->line('');
        $this->info('items.current_stock reset to 0, naming_series.current_number reset to 0.');
        $this->line('Run: php artisan cleanup:testing-data verify');

        return self::SUCCESS;
    }

    // ------------------------------------------------------------------
    // TAHAP 5 — VERIFY
    // ------------------------------------------------------------------
    private function runVerify(): int
    {
        $this->info('Transactional tables (expect 0 rows each):');
        $rows = $this->countRows(self::DELETE_ORDER);
        $this->table(['Table', 'Rows'], $rows);
        $nonZero = array_filter($rows, fn ($r) => $r[1] !== 0);
        if ($nonZero !== []) {
            $this->error('Some transactional tables are NOT empty — investigate before trusting this cleanup.');
        }

        $this->line('');
        $this->info('Master tables (compare against your Tahap 2 counts — must be unchanged):');
        $this->table(['Table', 'Rows'], $this->countRows(self::MASTER_TABLES));

        $this->line('');
        $badStock = DB::table('items')->where('current_stock', '!=', 0)->count();
        $badSeries = DB::table('naming_series')->where('current_number', '!=', 0)->count();
        $this->line("Items with non-zero current_stock: {$badStock} (expect 0)");
        $this->line("Naming series with non-zero current_number: {$badSeries} (expect 0)");

        $this->line('');
        $this->warn('Also load the app in a browser now: Dashboard, Sales Orders, Purchase Orders, Maintenance, Administration — confirm none of them error on empty data.');

        return self::SUCCESS;
    }

    /** @param array<int, string> $tables @return array<int, array{0: string, 1: int}> */
    private function countRows(array $tables): array
    {
        return array_map(fn ($t) => [$t, DB::table($t)->count()], $tables);
    }

    /** @param array<int, string> $tables @return array<string, int> */
    private function snapshotCounts(array $tables): array
    {
        return collect($tables)->mapWithKeys(fn ($t) => [$t => DB::table($t)->count()])->all();
    }
}
